name: Jekyll Deploy

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'Gemfile'
            - 'README.md'
            - 'LICENSE.md'
    workflow_dispatch: # Allows a run of this workflow to be triggerred manually from the Actions tab
# Build site using jekyll
jobs:
    jekyll:
        runs-on: ubuntu-latest
        steps:
            - name: 📂 setup
              uses: actions/checkout@v3

            - name: 💎 setup ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.1.3

            - name: 🤖 setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm install

            - name: 🔨 install dependencies & build site
              uses: limjh16/jekyll-action-ts@v2
              with:
                  enable_cache: false
                  ### Enables caching. Similar to https://github.com/actions/cache.

            - name: 🚀 deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_site
